<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cr1</string>
		<string>CR1</string>
		<string>cr2</string>
		<string>CR2</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)^\s*+\b(datatable|displaymenu|sub|submenu|beginprog)\b.*</string>
	<key>foldingStopMarker</key>
	<string>(?i)^\s*+(endtable|endmenu|endsub|endsubmenu|endprog).*</string>
	<key>name</key>
	<string>CRBasic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>'.*\n</string>
			<key>name</key>
			<string>comment.line.quote.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(if|then|endif|else|elseif)\b</string>
			<key>name</key>
			<string>keyword.control.all.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*|\+|\-|=|/|\^)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(and|or|xor)\b</string>
			<key>name</key>
			<string>keyword.operator.boolean.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&gt;|&lt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(pipelinemode|slowsequence)\b</string>
			<key>name</key>
			<string>keyword.other.all.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>punctuation.section.function.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\".*\"</string>
			<key>name</key>
			<string>string.quoted.double.crbasic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.all.crbasic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.all.crbasic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.crbasic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.crbasic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(units)\s+(\w+)\s*(=)\s*([\w \/%\^]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(abs|acceptdatarecords|acos|addprecise|am25t|as|average|battery|brhalf|call|calltable|datainterval|delay|displaymenu|displayvalue|endmenu|endsub|endsubmenu|endprog|endtable|fieldnames|getvariables|iftime|log|maximum|minimum|modbusmaster|movebytes|nextscan|nextsubscan|not|paneltemp|portset|pulsecount|realtime|sample|scan|sdi12recorder|senddata|serialclose|serialflush|serialin|serialinblock|serialopen|serialoutblock|splitstr|subscan|submenu|stddev|sw12|tcdiff|tcpopen|therm108|totalize|voltdiff|voltse|windvector)\b</string>
			<key>name</key>
			<string>support.function.all.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(com\d|_\d+hz|comsdc\d|true|false|nan|mv\d+|vx\d)\b</string>
			<key>name</key>
			<string>support.constant.all.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(const|dim|ieee4|public|long|string|float|fp2|alias)\b</string>
			<key>name</key>
			<string>support.type.all.crbasic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.sub.crbasic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.function.all.crbasic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(sub)\s+(\w+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.datatable.crbasic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.datatable.all.crbasic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(datatable)\((Archive)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bbeginprog\b</string>
			<key>name</key>
			<string>support.function.beginprog.crbasic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+</string>
			<key>name</key>
			<string>variable.other.all.crbasic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.crbasic</string>
	<key>uuid</key>
	<string>AB3DC169-9A84-4388-9483-B2CBA0CA6156</string>
</dict>
</plist>
